import type { Metadata } from "next";
import { CheckCircle2, Eye, HeartHandshake, Lightbulb, Target } from "lucide-react";
import { CTA, PageHero, SectionHeading } from "@/components/marketing/shared";
import { ScrollReveal } from "@/components/marketing/scroll-reveal";

export const metadata: Metadata = { title: "About us | GetDarsgah", description: "Why GetDarsgah is building a clearer, more connected way to run schools." };

export default function AboutPage() {
  return <div className="marketing-home">
    <ScrollReveal />
    <div data-reveal><PageHero eyebrow="About GetDarsgah" title={<>Technology should make<br /><span className="text-primary">school feel simpler.</span></>} description="We are building Darsgah to give education teams the clarity, structure, and time they need to focus on the work that matters." /></div>
    <section data-reveal className="marketing-container grid items-center gap-14 py-24 lg:grid-cols-2">
      <div><SectionHeading eyebrow="Our perspective" title="Schools deserve software shaped around their reality." description="School operations are deeply connected, but the tools used to run them often are not. Student records live in one place, attendance in another, finance in spreadsheets, and approvals in conversations that are difficult to trace." /><div className="mt-8 grid gap-3 sm:grid-cols-2">{["One connected source of truth", "Designed for every school role"].map((point) => <p key={point} className="flex items-center gap-2 text-sm font-semibold text-slate-700"><CheckCircle2 className="h-5 w-5 text-primary" />{point}</p>)}</div></div>
      <div className="marketing-card relative overflow-hidden rounded-[28px] border border-primary-ink bg-gradient-to-br from-primary to-[#163d85] p-8 text-white shadow-[0_22px_56px_rgba(37,99,235,0.24)] sm:p-10"><div className="absolute -right-10 -top-10 h-40 w-40 rounded-full bg-cyan-200/20 blur-2xl" /><div className="relative"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/15 text-white ring-1 ring-white/20"><Lightbulb className="h-5 w-5" /></span><p className="mt-8 text-xl font-semibold leading-9 tracking-tight text-white sm:text-2xl">Darsgah brings those moving parts together in a system that feels calm, predictable, and understandable to the people using it every day.</p><div className="mt-8 border-t border-white/20 pt-5 text-xs font-bold uppercase tracking-[0.16em] text-blue-100">Clarity for every school day</div></div></div>
    </section>
    <section data-reveal className="border-y border-slate-200 bg-slate-50"><div className="marketing-container py-24"><SectionHeading eyebrow="What guides us" title="Principles behind the product" centered /><div className="mt-14 grid gap-5 md:grid-cols-3"><Principle icon={Eye} title="Clarity first" text="People should understand where they are, what needs attention, and what happens next." tone="blue" /><Principle icon={Target} title="Useful by default" text="Every feature should solve a real operational problem, not simply add another screen." tone="violet" /><Principle icon={HeartHandshake} title="Built with respect" text="We design for busy school teams and the responsibility they carry every day." tone="cyan" /></div></div></section>
    <section data-reveal className="marketing-container grid gap-12 py-24 lg:grid-cols-[0.8fr_1.2fr]"><div><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary text-white shadow-button"><Lightbulb className="h-5 w-5" /></span><p className="mt-6 text-xs font-bold uppercase tracking-[0.16em] text-primary">Our mission</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-ink">Better operations, more room for education.</h2></div><p className="rounded-[28px] border border-primary-ink bg-gradient-to-br from-primary to-[#16478f] p-7 text-2xl font-medium leading-10 tracking-tight text-white shadow-[0_18px_44px_rgba(37,99,235,0.22)] sm:p-10 sm:text-3xl sm:leading-[1.45]">To help schools operate with greater clarity by connecting their people, information, and everyday workflows in one dependable system.</p></section>
    <div data-reveal><CTA title="Build a clearer way of working" description="Talk with us about your school's current process and where Darsgah can remove friction." /></div>
  </div>;
}
function Principle({ icon: Icon, title, text, tone }: { icon: typeof Eye; title: string; text: string; tone: "blue" | "violet" | "cyan" }) { const styles = { blue: "bg-primary-soft text-primary", violet: "bg-violet-50 text-violet-700", cyan: "bg-cyan-50 text-cyan-700" }; return <article data-reveal className="marketing-card marketing-feature-card rounded-[22px] border border-slate-200 bg-white p-7"><span className={`flex h-12 w-12 items-center justify-center rounded-2xl ${styles[tone]}`}><Icon className="h-6 w-6" /></span><h3 className="mt-6 text-lg font-bold text-ink">{title}</h3><p className="mt-3 text-sm leading-6 text-muted">{text}</p></article>; }
