import type { ReactNode } from "react";
import { cn } from "@/lib/utils";
import type { BillingStatus, PlatformSchoolStatus } from "@/lib/services/platform";

export function PlatformHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) { return <div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-primary">{eyebrow}</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.035em] text-ink sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">{description}</p></div>{action}</div>; }
export function StatusBadge({ status }: { status: PlatformSchoolStatus | BillingStatus }) { const styles: Record<string, string> = { active: "bg-success-soft text-green-700", trial: "bg-primary-soft text-primary", trialing: "bg-primary-soft text-primary", suspended: "bg-warning-soft text-amber-700", past_due: "bg-danger-soft text-danger", archived: "bg-slate-100 text-slate-600", cancelled: "bg-slate-100 text-slate-600" }; return <span className={cn("inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider", styles[status])}>{status.replace("_", " ")}</span>; }
export function StatCard({ label, value, note, icon }: { label: string; value: string | number; note: string; icon: ReactNode }) { return <div className="rounded-[18px] border border-slate-200 bg-white p-5 shadow-[0_8px_24px_rgba(15,23,42,0.04)]"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-muted">{label}</p><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary-soft text-primary">{icon}</span></div><p className="mt-4 text-3xl font-bold tracking-tight text-ink">{value}</p><p className="mt-2 text-[11px] text-muted">{note}</p></div>; }
export function Empty({ children }: { children: ReactNode }) { return <div className="rounded-[20px] border border-dashed border-slate-300 bg-white px-6 py-16 text-center text-sm text-muted">{children}</div>; }
export function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(value)) : "Not set"; }
