import React from "react";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import ReportDownloadLink from "./ReportDownloadLink";
const renderPdf = vi.hoisted(() => vi.fn());
vi.mock("@react-pdf/renderer", () => ({ pdf: renderPdf, StyleSheet: { create: (value: unknown) => value } }));
vi.mock("./StaffReportPDF", () => ({ StaffReportPDF: () => null }));
vi.mock("./StudentReportPDF", () => ({ StudentReportPDF: () => null }));
vi.mock("./report-logo", () => ({ loadReportLogo: async () => null }));
beforeEach(() => { vi.stubGlobal("React", React); });
afterEach(() => { cleanup(); vi.clearAllMocks(); vi.unstubAllGlobals(); });
it("opens the profile action modal without generating and allows retry", async () => {
  renderPdf.mockImplementation(() => { throw new Error("Render failed"); });
  render(<ReportDownloadLink type="staff" data={{ fullName: "Ali", status: "active", staffId: "42", role: "Teacher" }} generatedAt="2026-09-24T07:00:00Z" onRetry={() => {}} />);
  expect(screen.getByRole("dialog")).toBeTruthy();
  expect(renderPdf).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole("button", { name: "Download PDF" }));
  await screen.findByRole("alert");
  fireEvent.click(screen.getByRole("button", { name: "Download PDF" }));
  await waitFor(() => expect(renderPdf).toHaveBeenCalledTimes(2));
});
