import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { createSchoolAction } from "@/app/(platform)/platform/actions";
import { PlatformHeader } from "@/components/platform/platform-ui";

export const metadata: Metadata = { title: "Add school | GetDarsgah platform" };
export default function NewSchoolPage() { return <><PlatformHeader eyebrow="Tenant onboarding" title="Add a school" description="Create the tenant, initial principal login, and subscription record in one setup." action={<Link href="/platform/schools" className="inline-flex items-center gap-2 text-sm font-bold text-muted"><ArrowLeft className="h-4 w-4" />Back</Link>} /><form action={createSchoolAction} className="max-w-3xl rounded-[20px] border border-slate-200 bg-white p-6 shadow-soft sm:p-8"><Section title="School details"><div className="grid gap-5 sm:grid-cols-2"><Field label="School name" name="name" placeholder="The Learning School" /><Field label="URL slug" name="slug" placeholder="the-learning-school" hint="Spaces and capitals are converted automatically." /><Field label="Primary contact" name="contactName" placeholder="Contact name" /><Field label="Contact email" name="contactEmail" type="email" placeholder="admin@school.edu" /><label className="grid gap-2 text-xs font-bold text-ink">Timezone<select name="timezone" defaultValue="Asia/Karachi" className="platform-input"><option value="Asia/Karachi">Asia/Karachi</option><option value="UTC">UTC</option><option value="Asia/Dubai">Asia/Dubai</option><option value="Europe/London">Europe/London</option></select></label></div></Section><Section title="Initial principal account"><div className="grid gap-5 sm:grid-cols-2"><Field label="Principal name" name="principalName" placeholder="Full name" /><Field label="Principal email" name="principalEmail" type="email" placeholder="principal@school.edu" /><label className="grid gap-2 text-xs font-bold text-ink sm:col-span-2">Temporary password<input className="platform-input" required minLength={12} name="temporaryPassword" type="password" autoComplete="new-password" placeholder="At least 12 characters" /><span className="font-normal text-muted">The principal must change this password on first sign-in.</span></label></div></Section><Section title="Subscription"><div className="grid gap-5 sm:grid-cols-2"><Select label="Initial access" name="platformStatus" options={[["trial", "Trial"], ["active", "Active"]]} /><Select label="Plan" name="subscriptionPlan" options={[["school", "Darsgah School"], ["network", "Darsgah Network"], ["custom", "Custom"]]} /><Select label="Billing status" name="billingStatus" options={[["trialing", "Trialing"], ["active", "Active"]]} /><label className="grid gap-2 text-xs font-bold text-ink">End or renewal date<input className="platform-input" name="subscriptionEndsAt" type="date" /></label></div></Section><div className="flex justify-end border-t border-slate-200 pt-6"><button className="rounded-xl bg-primary px-6 py-3 text-sm font-bold text-white shadow-button">Create school and principal</button></div></form></>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mb-8"><h2 className="mb-5 text-sm font-bold text-ink">{title}</h2>{children}</section>; }
function Field({ label, name, placeholder, type = "text", hint }: { label: string; name: string; placeholder: string; type?: string; hint?: string }) { return <label className="grid gap-2 text-xs font-bold text-ink">{label}<input className="platform-input" required={["name", "slug", "principalName", "principalEmail"].includes(name)} name={name} type={type} placeholder={placeholder} />{hint ? <span className="font-normal text-muted">{hint}</span> : null}</label>; }
function Select({ label, name, options }: { label: string; name: string; options: string[][] }) { return <label className="grid gap-2 text-xs font-bold text-ink">{label}<select className="platform-input" name={name}>{options.map(([value, text]) => <option value={value} key={value}>{text}</option>)}</select></label>; }
