"use client";

import { useActionState } from "react";
import { ArrowRight, CheckCircle2, LoaderCircle } from "lucide-react";
import { submitInternalQueryAction } from "@/app/(app)/help/actions";

export function InternalQueryForm() {
  const [state, action, pending] = useActionState(submitInternalQueryAction, { status: "idle", message: "" });
  if (state.status === "success") return <div className="flex min-h-[360px] flex-col items-center justify-center text-center"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-success-soft text-success"><CheckCircle2 className="h-7 w-7" /></span><h2 className="mt-5 text-xl font-bold text-ink">Query sent</h2><p className="mt-2 max-w-sm text-sm leading-6 text-muted">Your school leadership will be able to review it. You can send another query tomorrow.</p></div>;
  return <form action={action} className="grid gap-5"><label className="grid gap-2 text-sm font-bold text-ink">Send to<select name="assigned_role" defaultValue="principal" className="h-12 rounded-xl border border-outline bg-white px-4 text-sm font-normal text-ink"><option value="principal">Principal</option><option value="administrator">Administrator</option></select></label><label className="grid gap-2 text-sm font-bold text-ink">Subject<input name="subject" required maxLength={160} placeholder="What do you need help with?" className="h-12 rounded-xl border border-outline bg-white px-4 text-sm font-normal text-ink" /></label><label className="grid gap-2 text-sm font-bold text-ink">Your query<textarea name="message" required minLength={10} maxLength={3000} rows={6} placeholder="Explain what you were trying to do and where you got stuck." className="resize-none rounded-xl border border-outline bg-white px-4 py-3 text-sm font-normal text-ink" /></label>{state.message ? <p className="rounded-xl bg-danger-soft px-4 py-3 text-sm font-semibold text-danger">{state.message}</p> : null}<button disabled={pending} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-primary px-6 text-sm font-bold text-white shadow-button disabled:opacity-60">{pending ? <><LoaderCircle className="h-4 w-4 animate-spin" />Sending…</> : <>Send query <ArrowRight className="h-4 w-4" /></>}</button><p className="text-center text-xs text-muted">To keep requests manageable, each staff account can send one query per day.</p></form>;
}
