import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, ChevronDown } from "lucide-react";
import { PageHero } from "@/components/marketing/shared";
import { PricingComparison, PricingSection } from "@/components/marketing/pricing-section";
import { pricingFaqs } from "@/components/marketing/pricing-data";

export const metadata: Metadata = { title: "Pricing | GetDarsgah", description: "Simple, fair Darsgah plans for schools of every size." };

export default function PricingPage() { return <>
  <PageHero eyebrow="Simple pricing" title={<>The right plan for<br /><span className="text-primary">your school.</span></>} description="Simple. Fair. Scalable. Explore plans for small schools, growing teams, and multi-campus operations." />
  <section className="mx-auto w-[min(100%_-_2rem,_1700px)] py-16 sm:w-[min(100%_-_3rem,_1700px)] sm:py-20"><PricingSection /></section>
  <section className="border-y border-slate-200 bg-slate-50"><div className="mx-auto w-[min(100%_-_2rem,_1700px)] py-16 sm:w-[min(100%_-_3rem,_1700px)] sm:py-20"><div className="mx-auto mb-10 max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Compare plans</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-ink">Everything, at a glance.</h2></div><PricingComparison /></div></section>
  <section className="marketing-container py-16 sm:py-20"><div className="rounded-3xl border border-blue-100 bg-primary-soft p-8 sm:p-12"><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Custom development</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-ink">Need a solution built around your school?</h2><p className="mt-4 max-w-3xl leading-7 text-muted">Yes, we can customize Darsgah or build a tailored school management solution around your requirements. The cost varies depending on the features, workflows, integrations, and scope of work you need.</p><p className="mt-4 text-sm font-semibold text-ink">Custom development is quoted separately and is not automatically included in a subscription.</p><Link href="/contact?enquiry=custom-development" className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-full bg-primary px-6 text-sm font-bold text-white hover:bg-primary-ink">Discuss your requirements <ArrowRight className="h-4 w-4" /></Link></div></section>
  <section className="marketing-container py-16"><div className="mx-auto max-w-3xl"><div className="mb-8 text-center"><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Pricing FAQs</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-ink">Questions, answered clearly.</h2></div><div className="divide-y divide-slate-200 border-y border-slate-200">{pricingFaqs.map(([question, answer]) => <details key={question} className="group py-1"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 py-5 font-bold text-ink"><span>{question}</span><ChevronDown className="h-5 w-5 shrink-0 text-muted transition-transform group-open:rotate-180" /></summary><p className="pb-6 pr-10 text-sm leading-7 text-muted">{answer}</p></details>)}</div></div></section>
  <section className="border-t border-slate-200 bg-slate-50"><div className="marketing-container py-16 text-center"><h2 className="text-3xl font-bold tracking-tight text-ink">Ready to find the right fit?</h2><p className="mx-auto mt-4 max-w-xl text-muted">Book a demo and we will discuss your school&apos;s requirements and next steps.</p><Link href="/contact" className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-full bg-primary px-6 text-sm font-bold text-white hover:bg-primary-ink">Book a demo <ArrowRight className="h-4 w-4" /></Link></div></section>
</>; }
