import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Building2, School } from "lucide-react";
import { CheckItem, PageHero } from "@/components/marketing/shared";

export const metadata: Metadata = { title: "Pricing | GetDarsgah", description: "Simple Darsgah pricing shaped around your school's size and operational needs." };

export default function PricingPage() {
  return <>
    <PageHero eyebrow="Simple pricing" title={<>The right setup for<br /><span className="text-primary">your school.</span></>} description="Every school works differently. We tailor the rollout to your student count, modules, and implementation needs, with no confusing feature maze." />
    <section className="marketing-container py-20">
      <div className="mx-auto grid max-w-5xl gap-6 lg:grid-cols-2">
        <PricingCard icon={School} label="For individual schools" title="Darsgah School" description="A complete operational workspace for one school and its team." points={["Student and staff management", "Attendance and academics", "Fees, finance, and payroll", "Reports and approvals", "Role-based team access", "Guided onboarding"]} />
        <PricingCard icon={Building2} label="For school groups" title="Darsgah Network" description="A tailored setup for organizations managing multiple campuses or schools." points={["Everything in Darsgah School", "Multi-school implementation planning", "Standardized operational workflows", "Coordinated onboarding", "Priority implementation support", "Tailored data migration plan"]} featured />
      </div>
      <p className="mx-auto mt-8 max-w-2xl text-center text-xs leading-5 text-muted">Pricing is provided after a short discovery call so we can recommend the right implementation instead of charging you for capacity or services you do not need.</p>
    </section>
    <section className="border-y border-slate-200 bg-slate-50"><div className="marketing-container py-20 text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">What happens next</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-ink">A clear path from demo to launch</h2><div className="mx-auto mt-12 grid max-w-4xl gap-6 md:grid-cols-3"><Step n="01" title="Discovery" text="We learn how your school works today." /><Step n="02" title="Walkthrough" text="We map Darsgah to your key workflows." /><Step n="03" title="Proposal" text="You receive a clear scope and price." /></div></div></section>
    <section className="marketing-container py-20 text-center"><h2 className="text-3xl font-bold tracking-tight text-ink">Let&apos;s find the right fit.</h2><p className="mx-auto mt-4 max-w-xl text-muted">Tell us about your school and we will prepare a focused walkthrough and pricing conversation.</p><Link href="/contact" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-xl bg-primary px-6 text-sm font-bold text-white shadow-button hover:bg-primary-ink">Talk to our team <ArrowRight className="h-4 w-4" /></Link></section>
  </>;
}
function PricingCard({ icon: Icon, label, title, description, points, featured = false }: { icon: typeof School; label: string; title: string; description: string; points: string[]; featured?: boolean }) { return <article className={`marketing-card relative rounded-[24px] border p-7 sm:p-9 ${featured ? "border-primary bg-[#0f2652] text-white shadow-[0_24px_70px_rgba(15,38,82,0.18)]" : "border-slate-200 bg-white"}`}>{featured ? <span className="absolute right-6 top-6 rounded-full bg-white/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-blue-100">Multi-campus</span> : null}<Icon className={featured ? "h-7 w-7 text-blue-300" : "h-7 w-7 text-primary"} /><p className={`mt-7 text-xs font-bold uppercase tracking-[0.16em] ${featured ? "text-blue-200" : "text-primary"}`}>{label}</p><h2 className="mt-3 text-3xl font-bold tracking-tight">{title}</h2><p className={`mt-3 text-sm leading-6 ${featured ? "text-blue-100/75" : "text-muted"}`}>{description}</p><p className="mt-8 text-2xl font-bold">Custom pricing</p><Link href="/contact" className={`mt-5 flex min-h-12 items-center justify-center gap-2 rounded-xl text-sm font-bold ${featured ? "bg-white text-[#0f2652]" : "bg-primary text-white shadow-button"}`}>Request a quote <ArrowRight className="h-4 w-4" /></Link><ul className={`mt-8 space-y-3 border-t pt-7 ${featured ? "border-white/10 [&_li]:text-blue-50/80" : "border-slate-100"}`}>{points.map(point => <CheckItem key={point}>{point}</CheckItem>)}</ul></article>; }
function Step({ n, title, text }: { n: string; title: string; text: string }) { return <div><span className="text-3xl font-bold text-blue-200">{n}</span><h3 className="mt-3 font-bold text-ink">{title}</h3><p className="mt-2 text-sm text-muted">{text}</p></div>; }
